### ISSUE TITLE
Jinja2 code in static JS file causes javascript syntax error

### ISSUE THREAD

**Issue by cisko3000** [paris3200/flask-inventory#14]
There's this url_for() function in static file 'main.js', it causes invalid syntax JavaScript error in console.

```
// custom javascript
$(document).ready(function() {
    $.ajax({
        url: '{{ url_for("vendor.search") }}'
    }).done(function (data) {
        $('input').autocomplete({
            source: data,
            minLength: 2
        });
    });
}
```

Possible solution is declaring SCRIPT_ROOT variable in base template
`<script>$SCRIPT_ROOT = {{ request.script_root|tojson|safe }}; </script>`
Then one can use $SCRIPT_ROOT in static js files to know the root URL and hard-code rest of route.
This is what I always do in my projects.

Any other suggestions?

**Comment by paris3200** [comment]
I don't see why that solution wouldn't work.

**Comment by cisko3000** [comment]
Hi paris3200, how do I self assign this? is it possible or do you have to assign it?

**Comment by paris3200** [comment]
I'm not sure if you can assign it or not.  I went ahead and assigned it to you.

**Comment by cisko3000** [comment]
Hey I fixed this, deleted the custom javascript code. I investigated and I don't think it was actually doing anything.
